name: UVM Regression Run (Manual)

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually via a button in the Actions tab

jobs:
  uvm-regression:
    runs-on: sanity-builder
    environment: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run UVM regression
        run: |
          bash ci/uvm_regression.sh
      
      - name: Print contents of summary.txt to Workflow Page
        if: always()
        run: |
          echo '## UVM Regression Pass/Fail Summary' >> $GITHUB_STEP_SUMMARY
          if [ -f uvm_regression_logs/summary.md ]; then
            cat uvm_regression_logs/summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No summary.md file found." >> $GITHUB_STEP_SUMMARY
          fi